# Numpy tutorial

In [32]:
import numpy as np
a = np.array([1,2,3])
print(type(a))
print(a.shape)
print(a.ndim)
print("................")
b = np.array([[1,2,3],[2,2,2],[3,5,7]])
print(type(b))
print(b.shape)
print(f'dimencion',b.ndim)
#print(b[1,0],b[2,1],b[3,2])

<class 'numpy.ndarray'>
(3,)
1
................
<class 'numpy.ndarray'>
(3, 3)
dimencion 2


* Operaciones - matrix

In [31]:
x = np.array([[1,2],[3,5]], dtype= np.float64)
y = np.array([[5,6],[7,8]],dtype= np.float64)
print(x+y)

[[ 6.  8.]
 [10. 13.]]


* Producto Dot

In [36]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11,12])

# Producto interto de vectores
print(v.dot(w))
print(np.dot(v,w))
# Matrix / vector producto;
print(x.dot(y))
print(np.dot(x,y))

219
219
[[19 22]
 [50 58]]
[[19 22]
 [50 58]]


# slicing

In [54]:
#
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

b=a[:2,1:3]
print(b)

[[2 3]
 [6 7]]


* Indexing

In [75]:
a = np.array([[1,2],[3,4],[5,6]])
print(a[[0,1,2],[0,1,0]])
print(np.array(a[2,0]))
print(f'dimencion',a.shape)

[1 4 5]
5
dimencion (3, 2)


* Bool index

In [82]:
a = np.array([[1,2],[3,4],[1,6]])
bool_idx =(a>=2)
print(bool_idx)
print(a[bool_idx])
print(a[a>2])

[[False  True]
 [ True  True]
 [False  True]]
[2 3 4 6]
[3 4 6]


* Suma con numpy

In [85]:
a = np.array([[1,2],[3,4],[1,6]])
print(np.sum(a))
print(np.sum(a,axis=0))
print(np.sum(a,axis=1))

17
[ 5 12]
[3 7 7]


* Reshape

In [109]:
a = np.array([[1,2],[3,4],[1,6]])
array = np.arange(8).reshape(4,2)
print(array)
print("...............")
# Construcir 3D array
array1= np.arange(8).reshape(2,2,2)
print(f'\nOriginal! array reshape to 3d ',array1)


[[0 1]
 [2 3]
 [4 5]
 [6 7]]
...............

Original! array reshape to 3d  [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


* reshaped

In [125]:
from  numpy import array, reshape
from  numpy import reshape
# lista de datos
data = [[11,22,3],[33,44,5],[55,66,7]]

# array de datos
data = array(data)
print("Rows: %d" % data.shape[0])
print(data.shape)

Rows: 3
(3, 3)


# Tensors 1D,2D,3D

In [126]:
# tensor scalar - OD TENSOR
x = np.array(12)
print(x.ndim)

0


* Tensor 1D

In [132]:
a= np.array([100,200,300])
print(a.ndim)

1


* Tensro 2D


In [136]:
a=np.array([[11,22,3],
            [33,44,5],
           [1,5,7] ])
print(a.ndim)

2


* Tensor 3D

In [138]:
a=np.array([
                [
                    [11,22,3],
                    [33,44,5],
                    [55,66,7]
                ],
               [
                   [11,22,3],
                    [33,44,5],
                    [55,66,7]
               ],
                 [
                   [1,22,3],
                    [3,44,5],
                    [5,66,7]
               ],

            ])
print(a.ndim)

3


* In deep learning , generalmente se manipula tensores entre )D to- 4D

In [141]:
import keras_datasets as kras
from keras_datasets import

(train_images, train_labels),(tes_images, test_labels)=mnist.load_data()
print(train_images.shape)


ImportError: cannot import name 'mnist' from 'keras_datasets' (C:\Users\JAVIER\PycharmProjects\entorno_general_py\lib\site-packages\keras_datasets\__init__.py)

# Casi terminado np